### ISSUE TITLE
Neues Benutzerkonto - Keine Bestätigung

### ISSUE THREAD

**Issue by LukiLeu** [szeberli/youngstarswiki-bf#17]
Beim erstellen einesn Benutzerkontos folgt keine Mailbestätigung obwohl diese Meldung erscheint.
![image](https://user-images.githubusercontent.com/3243291/97080581-b0f94480-15fc-11eb-9025-02b55d253f31.png)

**Comment by robinaustiin** [comment]
funktioniert erst wenn online
