### ISSUE TITLE
Neuer Artikel - Fehlermeldung kein Absatz und keine Kategorie

### ISSUE THREAD

**Issue by LukiLeu** [szeberli/youngstarswiki-bf#21]
Wird kein Absatz und keine Kategorie bein einem neuen Artikel gewählt so erscheint folgende Fehlermeldung:
![image](https://user-images.githubusercontent.com/3243291/97081110-8a3d0d00-1600-11eb-988c-074b2644061a.png)

Jedoch wird beim klicken auf den entsprechenden Hyperlink im Fehler nicht zum fehlerhaften Element gesprungen.

**Comment by szeberli** [comment]
Wenn man nichts auswählt welches Pflichtfeld ist, dann kommt diese fehlermeldung.
