### ISSUE TITLE
Inhaltübersicht - Flaggen

### ISSUE THREAD

**Issue by LukiLeu** [szeberli/youngstarswiki-bf#24]
Wir die Inhaltsübersicht nicht über den gesamten Bildschirm dargestellt, so kleben die Flaggen von den beiden Reihen direkt aneinander

![image](https://user-images.githubusercontent.com/3243291/97082074-32ee6b00-1607-11eb-9430-088f51858c36.png)

**Comment by robinaustiin** [comment]
nicht relevant
