### ISSUE TITLE
Keine Abfrage nach Bildrechten bei Anrisstext-Hintergrund

### ISSUE THREAD

**Issue by BRsmover** [szeberli/youngstarswiki-bf#26]
Wenn ein Abschnitt "Anrisstext" hinzugefügt wird und dort im Register "Hintergrund" ein Bild hochgeladen wird, bekommt der User keine Checkbox um zu bestätigen, dass er die Bildrechte besitzt.

**Comment by robinaustiin** [comment]
Checkbox zur Abfrage hinzugefügt
