### ISSUE TITLE
Grafikfehler in Chrome

### ISSUE THREAD

**Issue by BRsmover** [szeberli/youngstarswiki-bf#27]
(Falls schon erfasst einfach löschen)

In Chrome werden die Sprachen, in welchen ein Artikel auch noch verfügbar ist, links statt wie in Firefox rechts dargestellt

Firefox (korrekt)
![image](https://user-images.githubusercontent.com/7579163/97580929-3b261c00-19f4-11eb-8cda-98ec98d773db.png)

Chrome
![image](https://user-images.githubusercontent.com/7579163/97580968-48dba180-19f4-11eb-84d7-7fd1e17c6362.png)

**Comment by robinaustiin** [comment]
Ist jetzt in Chrome auch rechts
