### ISSUE TITLE
Statistiken

### ISSUE THREAD

**Issue by BRsmover** [szeberli/youngstarswiki-bf#28]
[Zugehörigkeit im Lastenheft:  AS_016, AS_016b und AS_017]

Muss für Google Analytics unter _Konfiguration>System>Google Analytics_ noch mehr ausser der Web-Property-ID angegeben werden?

Wo kann man die Zugriffszähler, die unter _Konfiguration>System>Statistiken_ aktiviert wurden, ansehen?

**Comment by szeberli** [comment]
Wird beim veröffentlichen gemacht. 
bitte uns einrach eure Google E-Mail angeben. dann können wir euch eintragen.

**Comment by BRsmover** [comment]
Ok, danke für die Info. Ich werde das in die Wege leiten.
