### ISSUE TITLE
Dashboard - Nicht alle Inhalte dürfen alle user sehen.

### ISSUE THREAD

**Issue by szeberli** [szeberli/youngstarswiki-bf#3]
- [ ] Alle User drüfen nur "meine Inahlte" sehen

![grafik](https://user-images.githubusercontent.com/10152825/96574252-7f683c80-12cf-11eb-8290-8d7a40c92b2b.png)

**Comment by LukiLeu** [comment]
Auch Benutzerkonten sollten meiner MEinung nach nicht von normalen Benutzern eingesehen werden können: 
![image](https://user-images.githubusercontent.com/3243291/97080659-52809600-15fd-11eb-8b72-9c209d3202f8.png)

Kommentare sollten meiner Meinung nach auch nur die eigenen dargestellt werden.

**Comment by robinaustiin** [comment]
Bereichleiter, Verwalter und Administrator können es jetzt noch sehen
