### ISSUE TITLE
Menü "Artikel" kann nicht übersetzt werden

### ISSUE THREAD

**Issue by anjafritz** [szeberli/youngstarswiki-bf#30]
![Screenshot 2020-11-19 152142](https://user-images.githubusercontent.com/74413179/99678330-fd5c6680-2a7a-11eb-9af7-eb5997672fa0.png)
![Screenshot 2020-11-19 152236](https://user-images.githubusercontent.com/74413179/99678416-136a2700-2a7b-11eb-8734-1cd529d24e3a.png)

**Comment by robinaustiin** [comment]
Der Menüpunkt ist jetzt übersetzbar
