### ISSUE TITLE
Unterseiten verlinken

### ISSUE THREAD

**Issue by anjafritz** [szeberli/youngstarswiki-bf#32]
Bei einer einfachen Seite kann ich im Text eine andere Unterseite verlinken. Bei 'Englisch' funktioniert es aber nicht, es ist nur möglich mit einer deutschen Seite zu verlinken, ausser ich gebe den ganzen Link ein zur englischen Seite, was aber mühsam ist.
![Screenshot 2020-11-19 161222](https://user-images.githubusercontent.com/74413179/99687212-ae1b3380-2a84-11eb-9014-1e7b6f7c4899.png)
![Screenshot 2020-11-19 163118](https://user-images.githubusercontent.com/74413179/99687215-afe4f700-2a84-11eb-9686-6c538a7d8bd0.png)

**Comment by robinaustiin** [comment]
Das verwendetete Modul kann nur die standartmässige Sprache suchen also in diesem Fall Deutsch
