### ISSUE TITLE
grosse Abstände zwischen Abschnitte

### ISSUE THREAD

**Issue by anjafritz** [szeberli/youngstarswiki-bf#33]
Es gibt immer noch sehr grosse Abstände zwischen zwei Abschnitte/Paragraphen. Das Häckchen 'am oberen Abschnitt anheften' ist auch schon aktiviert.
![Screenshot 2020-11-19 164910](https://user-images.githubusercontent.com/74413179/99689516-5df1a080-2a87-11eb-826b-3e3a84442bbe.png)

**Comment by robinaustiin** [comment]
Sollte jetzt wieder funktionieren.
