### ISSUE TITLE
Benutzer - Eingaben

### ISSUE THREAD

**Issue by LukiLeu** [szeberli/youngstarswiki-bf#39]
Was sollte unter Eingaben zu finden sein? Die erstellten Artikel des Benutzers?

![image](https://user-images.githubusercontent.com/3243291/103439949-e4ca9900-4c41-11eb-9cf9-d4f68513f389.png)

**Comment by szeberli** [comment]
Benutzer welche mehr rechte haben, können ihre Eingaben in Webformularen sehen... das ist system standart.
