### ISSUE TITLE
Übersetzung des kurzen Infotexts

### ISSUE THREAD

**Issue by BRsmover** [szeberli/youngstarswiki-bf#42]
Bei der automatisierten Übersetzung ins Französische habe ich festgestellt, das der kurze Infotext, der zu Beginn der Artikel steht, nicht mit übersetzt wurde. Dies ist auch bei einem anderen Artikel der Fall.

![image](https://user-images.githubusercontent.com/7579163/108597913-b472c180-738b-11eb-9c3e-14f6c889a3cb.png)

**Comment by robinaustiin** [comment]
bei welchen Artikel ist das der Fall?
