### ISSUE TITLE
Registrierung

### ISSUE THREAD

**Issue by BRsmover** [szeberli/youngstarswiki-bf#44]
Gleich nach der Registrierung wird ein Mail versandt, das nur einen **Betreff** "Kontodetails für TheTestUser auf YoungstarsWik i" hat... - vor dem letzten "i" ist ein Abstand & ".org" wäre gut, wenn das auch noch dran wäre

Des Weiteren muss nirgendwo bestätigt werden, dass man die **AGB** gelesen & akzeptiert hat.

Nach dem Setzen des initialen Passworts wäre es gut, wenn z.B. ein Balken oben  mit einem Link zur Startseite eingeblendet würde. User, die sich das erste Mal einloggen finden den Weg (via Dashboard - zurück zur Website) nicht

**Comment by szeberli** [comment]
du kannst du Nutzungsbedigungen anpassen: /de/nutzungsbedingungen
