### ISSUE TITLE
Passwortvorschläge

### ISSUE THREAD

**Issue by BRsmover** [szeberli/youngstarswiki-bf#46]
![image](https://user-images.githubusercontent.com/7579163/108601762-919dd880-739e-11eb-82f3-bc55740dd45b.png)

Was sind konkret die Anforderungen für Passwörter?

12 Zeichen als Vorschlag finde ich zu lang - würde 8 schreiben, dafür aber Gross-/Kleinschreibung & Zahlen noch vorschlagen

**Comment by szeberli** [comment]
Die Password Policy ist system standart eingestellt. 
mittels  Zwei-Faktor-Authentifizierung ist das sowiso bessser :)
