### ISSUE TITLE
Rolle Übersetzer

### ISSUE THREAD

**Issue by BRsmover** [szeberli/youngstarswiki-bf#49]
Können Übersetzer DeepL / Google zur automatisierten Übersetzung nutzen? Falls nicht: Kann man ihnen diese Berechtigung geben? / Wie? (hab's in der Rollenkonfiguration nicht gesehen)

**Comment by BRsmover** [comment]
Wir würden in der Startphase gerne allen Nutzern die Möglichkeit geben, DeepL/ Google Translate zu benützen und würden dann verfolgen, wie intensiv es genutzt wird.

**Comment by szeberli** [comment]
Das ist grunstätzlich möglich, die Kosten kann man einfach nicht absschätzen.....
