### ISSUE TITLE
PDF Button - Target

### ISSUE THREAD

**Issue by BRsmover** [szeberli/youngstarswiki-bf#50]
Das Klicken des PDF-Buttons sollte wenn möglich das PDF in einem neuen Tab öffnen
- à la _target="_blank"_ in HTML

**Comment by szeberli** [comment]
PDF wird heruntergeladen.

**Comment by BRsmover** [comment]
Ah sorry, das war eine Folge einer Chrome-Erweiterung meinerseits...
