### ISSUE TITLE
Kontaktformular

### ISSUE THREAD

**Issue by BRsmover** [szeberli/youngstarswiki-bf#51]
Wie kann ein erstelltes Formular verwendet werden? (z.B. "Kontaktiere uns!")

Wie können vom Formular "Kontakt" Felder geändert werden? z.B. der Empfänger - sehe es unter "Struktur > Kontaktformulare" nicht

![image](https://user-images.githubusercontent.com/7579163/108603119-5e5f4780-73a6-11eb-8266-08962d2e4770.png)

**Comment by szeberli** [comment]
Struktur -> Webformulare
/de/admin/structure/webform

ich habe dem Verwalter noch etwas mehr Rechte gegeben :)
