### ISSUE TITLE
Zugang Datenbank

### ISSUE THREAD

**Issue by BRsmover** [szeberli/youngstarswiki-bf#52]
Wie kann direkt auf die DB zugegriffen werden (z.B. für einen Export aller Nutzer) - evtl. auch erst nach Relaunch/Abnahme relevant

**Comment by szeberli** [comment]
nach dem Online gehen kannst du über das Panel auf die MySQL DB zugreifen. auf der Entwicklugns Umgebung ist das nicht möglich.

**Comment by BRsmover** [comment]
Alles klar, danke 👍
