### ISSUE TITLE
Persönliches Kontaktformular v. Nutzern

### ISSUE THREAD

**Issue by BRsmover** [szeberli/youngstarswiki-bf#53]
Nutzer können angeblich ein "Persönliches Kontaktformular" aktivieren

![image](https://user-images.githubusercontent.com/7579163/108603261-4b00ac00-73a7-11eb-90d9-db06373540f4.png)

Dieses ist aber nicht sichtbar...

![image](https://user-images.githubusercontent.com/7579163/108603273-594ec800-73a7-11eb-9344-e06b80b7139d.png)

**Comment by szeberli** [comment]
Dies ist eine Standart Komponente von Drupal - Soll ich das einfach deaktivieren?
dies wurde ja nirgends verlinkt...

**Comment by BRsmover** [comment]
Ja, du kannst es gerne deaktivieren 👍
