### ISSUE TITLE
Zweifaktorauthentifizierung

### ISSUE THREAD

**Issue by BRsmover** [szeberli/youngstarswiki-bf#54]
Wurde im Lastenheft nur als "BA" - Begeisterungsanforderung erfasst. Trotzdem die Frage: Kann man die aktivieren? Falls nicht: Wäre der Aufwand gross, das einzubauen?

**Comment by szeberli** [comment]
ist erledigt... beim User kannst du den Tab Sicherheit öffnen...

**Comment by BRsmover** [comment]
Sollte es bei allen aktiviert sein?

Ich sehe es nur beim Verwalter & dem Administrator.

Habe es für mein Admin-Konto eingerichtet und bekomme noch eine Fehlermeldung
![image](https://user-images.githubusercontent.com/7579163/109012768-a9cd6a80-76b2-11eb-9137-122da71633f3.png)

**Comment by szeberli** [comment]
@BRsmover
ist Korrigiert :) - Merci für den Hinweis
