### ISSUE TITLE
Darstellung Registrierungsfelder

### ISSUE THREAD

**Issue by BRsmover** [szeberli/youngstarswiki-bf#56]
Wenn man die Nutzungsbedingungen ansieht und zurückkehrt sehen die Felder für Mail & Name im ersten Moment, bis man reinklickt so aus:

![image](https://user-images.githubusercontent.com/7579163/109011431-26f7e000-76b1-11eb-8cfe-3469b3ca0f58.png)

Ist nicht schlimm aber leicht verwirrend...

**Comment by szeberli** [comment]
Das hat damit zu tun, dass der Bentuzer und Passwort vom Browser gepsiechert sind .... mal schauen ob wir das überseuten können :)
