### ISSUE TITLE
Ähnliche Artikel

### ISSUE THREAD

**Issue by LukiLeu** [szeberli/youngstarswiki-bf#58]
Die Bilder bei den ähnlichen Artikeln sind oftmals unterschiedlich gross. Könnte man diese allenfalls alle gleich hoch machen (zu diskutieren)

![image](https://user-images.githubusercontent.com/3243291/111210881-14950600-85ce-11eb-9bef-9e11408e47a5.png)

**Comment by BRsmover** [comment]
Die Bilder können leider nicht automatisiert zugeschnitten werden. 

Für den Relaunch würden wir aber sicher mal die auf der Startseite zuschneiden, damit der erste Eindruck sicher mal stimmt.

**Comment by szeberli** [comment]
@LukiLeu @BRsmover 
ja leider konnten wirdie Zuschnitte nicht auotmatisieren
