### ISSUE TITLE
Artikelübersicht

### ISSUE THREAD

**Issue by LukiLeu** [szeberli/youngstarswiki-bf#59]
Müssen diese Boxen alle unterschiedlich gross sein?

![image](https://user-images.githubusercontent.com/3243291/111211209-6dfd3500-85ce-11eb-9e9f-71b59e028b9b.png)

**Comment by BRsmover** [comment]
Die Boxen werden gemäss Simon per Flexbox dynamisch an die Grösde des Bildes und die Menge an Text im Infoabschnitt ganz oben im Artikel angepasst.

Es ist anders als wir's gewohnt sind aber ich finde es eine gute Lösung.
Zum einen machts Sinn, dass mehr Text = mehr Platz bedeutet, zum anderen bringt es etwas mehr Dynamik rein in die Startseite
