### ISSUE TITLE
Abschnitt doppelt vorhanden

### ISSUE THREAD

**Issue by LukiLeu** [szeberli/youngstarswiki-bf#61]
Im Artikel [https://yw-migration.computech.dev/de/wiki/artikel/abcd-schema](https://yw-migration.computech.dev/de/wiki/artikel/abcd-schema) ist der Abschnitt _4 H's_ doppelt vorhanden

**Comment by szeberli** [comment]
@LukiLeu Bitte mach nicht für jedes ein Ticket. Die Migration ist noch nicht fertig.
Sonst wird es sehr unübersichtlich für alle Tickets arbeiten vielen Dank fürs Verständnis￼
