### ISSUE TITLE
Suche in Sprache

### ISSUE THREAD

**Issue by LukiLeu** [szeberli/youngstarswiki-bf#62]
Sollte die Suche über alle Sprachen suchen oder nur innerhalb der aktuellen Sprache? Letzteres würde vermutlich mehr Sinn machen. Im Moment werden aber wenn z.B. Englisch als Sprache aktiviert ist auch die deutschen Artikel gefunden.

**Comment by szeberli** [comment]
@LukiLeu 
du kannst in der Suche Erweitert öffnen dann kannst du die Such eingränzen..

**Comment by LukiLeu** [comment]
Könnte man da allenfalls als Standart hinterlegen dass nur in der aktuell ausgewählten Sprache gesucht wird? Und man gezielt auswählen muss wenn man in mehreren Sprachen suchen möchte. Würde für mich eigentlich mehr Sinn machen.
