### ISSUE TITLE
Mehr Sponsoren hinzufügen

### ISSUE THREAD

**Issue by BRsmover** [szeberli/youngstarswiki-bf#63]
Ich habe drei Sponsoren. Ich sehe aber nicht, wie ich noch mehr hinzufügen kann, statt nur bestehende zu Editieren. Hast du da einen Tipp für mich?

**Comment by szeberli** [comment]
Inhalt-> hinzufügen-> Werbung
oder /de/node/add/werbung

**Comment by BRsmover** [comment]
Danke!
