### ISSUE TITLE
Ungarisch

### ISSUE THREAD

**Issue by anjafritz** [szeberli/youngstarswiki-bf#64]
Wo ist die Sprache Ungarisch im neuen YoungstarsWiki.org?
Es gab auch eingie Artikel in ungarisch, aber jetzt kann ich die Sprache bei der Sprachauswahl nicht finden. Wo sind diese ungarischen Artikel?

**Comment by BRsmover** [comment]
Ergänzungsfrage: Gibt es noch mehr Sprachen, die nicht mitgenommen wurden, aber Artikel hatten?

**Comment by szeberli** [comment]
- [ ] Wo ist die Sprache geblieben
- [ ] gibt es noch artikel

**Comment by GeMiSky** [comment]
Ungarisch HU installiert
