### ISSUE TITLE
Französisch

### ISSUE THREAD

**Issue by anjafritz** [szeberli/youngstarswiki-bf#65]
Bei der Sprache Französisch gibt es keine Angaben zu den Kategorien. Auf der Hauptseite erscheinen unten nicht die fünf Hauptkategorien Drop-Downs mit den einzelnen Unterkategorien. In den französischen Artikeln selber gibt es auch keine Angabe, zu welchen Unterkategorien der Artikel gehört. Bitte dies so bald als möglich beheben!!!

**Comment by robinaustiin** [comment]
das liegt daran das die Übersetzung der Taxonomy "Artikelkategorie" bisher nur in Engslish resp Deutsch gemacht wurde.

**Comment by robinaustiin** [comment]
sobald ein Taxonomybegriff übersetzt wurde wird dieser in der jeweiligen Sprache angezeigt

**Comment by robinaustiin** [comment]
Taxonomys sind jetzt alle übersetzt
