### ISSUE TITLE
Gleiche Namen der Unterkategorien in verschiedenen Hauptkategorien 

### ISSUE THREAD

**Issue by anjafritz** [szeberli/youngstarswiki-bf#66]
Es gibt insgesamt fünf Hauptkategorien: Non-Profit Organisation, Sport&Games, Outdoor, Creativity, Evangelism
Bei jeder dieser Hauptkategorien gibt es mehrere Unterkategorien. Teilweise gibt es in den verschiedenen Hauptkategorien Unterkategorien mit dem gleichen Namen. Ein Beispiel ist die Unterkategorien 'Camp'. Die gibt es in der Hauptkategorie 'Non-Profit Organisation' wie auch in der Hauptkategorie 'Creativity'. Nun ist es aktuell so, dass wenn ich in der Hauptkategorie 'Non-Profit Organisation' die Unterkategorie 'Camp' wähle, dann kommen dort die Artikel aus 'Non-Profit Organisation' wie auch aus 'Creativity', das gleiche ist umgekehrt der Fall. Das sollte so aber nicht sein, weil ich ja bewusst nur nach dem einen filtere. Das Problem ist, dass die URL nur nach der Unterkategorie aufgebaut ist und nicht die Unterscheidung in der Hauptkategorie macht - siehe hier im Beispiel: https://www.youngstarswiki.org/de/wiki/camp
Besser wäre es, wenn es zum Beispiel so wäre: www.youngstarswiki.org/de/wiki/npo/camp und www.youngstarswiki.org/de/wiki/creativity/camp

**Comment by robinaustiin** [comment]
gleiches Issue wie ["Evangelism Unterkategorie 'Seelsorge' #67"](https://github.com/szeberli/youngstarswiki-bf/issues/67)
