### ISSUE TITLE
Evangelism Unterkategorie 'Seelsorge'

### ISSUE THREAD

**Issue by anjafritz** [szeberli/youngstarswiki-bf#67]
Wenn ich bei der Hauptkategorie 'Evangelism' auf die Unterkategorie 'Seelsorge' klicke, dann komme ich nicht zu allen Artikel, welche zu dieser Unterkategorie gehört, sondern komme zu einem einzelnen Artikel mit dem Titel 'Seelsorge'. Das ist wohl darum, weil die URL folgend ist: https://www.youngstarswiki.org/de/wiki/seelsorge
Besser wäre, wenn dieser Artikel eine URL hätte wie beispielsweise: https://www.youngstarswiki.org/de/wiki/seelsorge/seelsorge

**Comment by szeberli** [comment]
@anjafritz 
die Taxonomies sind noch nicht übersetz:
https://www.youngstarswiki.org/de/admin/structure/taxonomy/manage/kategorie/overview

**Comment by BRsmover** [comment]
@szeberli 

Die Taxonomies/(Sub-)Kategorien habe ich mal alle übersetzt - ist das nicht übernommen worden/ ging das bei der Migration verloren?
