### ISSUE TITLE
Artikelzusammenfassung bei Bearbeitung unvollständig bei migrierten Artikeln

### ISSUE THREAD

**Issue by LukiLeu** [szeberli/youngstarswiki-bf#69]
Wird ein migrierter Artikel bearbeitet, so ist die Artikelzusammenfassung nachher unvollständig.

![image](https://user-images.githubusercontent.com/3243291/112032554-cedfbc80-8b3c-11eb-9ae9-a4b8769be311.png)
![image](https://user-images.githubusercontent.com/3243291/112032606-dc954200-8b3c-11eb-9ca8-a59c0d405bc1.png)

**Comment by szeberli** [comment]
@LukiLeu 
habe das soeben deaktiviert.
-> Wie sollen wir das handhaben?
a: DIe länge offen lassen
b: die Perosnen zwingen kürzere inhalte zu machen?
