### ISSUE TITLE
Sprache fällt auf Usersprache zurück

### ISSUE THREAD

**Issue by BRsmover** [szeberli/youngstarswiki-bf#70]
Wenn man die Sprache wechselt und danach z.B. nach einer Kategorie filtert, fällt die Sprachauswahl wieder auf die Usersprache zurück und man muss manuell die gewünschte Sprache erneut auswählen.

**Comment by szeberli** [comment]
![grafik](https://user-images.githubusercontent.com/10152825/112810395-42bd2000-907b-11eb-9880-e93c679f75d1.png)

- [ ] Sprachpräfix -> in der URL Mitgeben.
