### ISSUE TITLE
Unterkategorien in den Sprachen - Titel erscheinen immer auf Englisch

### ISSUE THREAD

**Issue by anjafritz** [szeberli/youngstarswiki-bf#72]
Wenn ich in einer Sprache wie zum Beispiel 'Niederländisch' bei den Kategorien im Dropdown auf eine Unterkategroie klicke wie beispielsweise bei 'Sport & Spel' auf 'Voetbal', dann erscheinen alle Artikel, die dieser Unterkategorie zugewiesen sind, aber oben im Titel steht es auf Englisch 'Soccer'.

**Comment by szeberli** [comment]
![grafik](https://user-images.githubusercontent.com/10152825/112808458-4780d480-9079-11eb-8c81-d2d09da96340.png)

**Comment by szeberli** [comment]
****
![grafik](https://user-images.githubusercontent.com/10152825/112808611-74cd8280-9079-11eb-8937-e2b2ff853910.png)

**Comment by robinaustiin** [comment]
Meistgesehene, neuste, etc. Artikel übersetzt

**Comment by robinaustiin** [comment]
Titel der View erscheint immernoch auf englisch
