### ISSUE TITLE
Dateinamen übersetzen

### ISSUE THREAD

**Issue by BRsmover** [szeberli/youngstarswiki-bf#73]
Dateinamen sind bei noch in der Originalsprache drin. Kann man die Dateien (inkl. Name) automatisiert Übersetzen.

**Comment by robinaustiin** [comment]
würde das Sinn machen?

**Comment by szeberli** [comment]
- [ ] Datei übersetzung Aktivieren. (so dass die Datein übersetzt werden können.
-> Dateidownload
