### ISSUE TITLE
Übersetzung 

### ISSUE THREAD

**Issue by szeberli** [szeberli/youngstarswiki-bf#77]
https://www.youngstarswiki.org/de/wiki/art/vertueueferli-rabe-aus-waescheklammer

- [ ] Inhalte werden komisch übersetzt und die Revision kann nicht zurückgesetzt werden

**Comment by BRsmover** [comment]
https://www.youngstarswiki.org/de/wiki/art/schatzkisten-kuchen

Artikel eigentlich DE - Nur Starttext noch deutsch der Rest übersetzt
