### ISSUE TITLE
Suche - Wortteile

### ISSUE THREAD

**Issue by robinaustiin** [szeberli/youngstarswiki-bf#8]
Wortteile werden mit der Suche nicht gefunden (z.B. "Jesus", was in "TestJesusTest" vorkommt oder "Kor", was in "1.Korinther" vorkommt)

**Comment by BRsmover** [comment]
Die Suche scheint noch immer nicht ganz userfreundlich zu sein. Um den Artikel "Heissluftballon" zu finden, muss nach genau dem Titel gesucht werden. Suchbegriffe wie "heissluftballone" kleingeschrieben, "heissluft" oder "Heissluft" finden den Artikel nicht. Auch die Vorschläge der Suche finden den Artikel nicht.

![image](https://user-images.githubusercontent.com/7579163/118780527-70109800-b88c-11eb-85e9-1e004d19b9db.png)

![image](https://user-images.githubusercontent.com/7579163/118780682-959da180-b88c-11eb-98ec-65993d2ed2c7.png)

**Comment by LukiLeu** [comment]
Das geht ins gleiche wie #80

**Comment by BRsmover** [comment]
> Das geht ins gleiche wie #80

Stimmt, danke. Hatte ich nicht gesehen
